version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: "~/sqs_logger/"
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}
            - cache-master
      - run:
          name: Install Dependencies
          command: |
            pip install -U -r requirements/base.txt --upgrade
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.cache/pip"
            - "~/.apt-cache"
      - run:
          name: Run tests
          command: make test
